server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1000707854714-cngtge6205i2gvgo3k3ppnn7tod1h6ta.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          facebook:
            client-id: 387671360308115
            client-secret: ea7ede9cffc3e294b047fec277ebd5d2
            scope:
              - email
              - public_profile

          naver:
            client-id: DNAmnZcfiG3Px8DKP7vB
            client-secret: Adt5N1YXNv
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키 값으로 네이버가 리턴해줌.


